name: C/C++ CI

on: [push]

jobs:
  Windows:
    runs-on: windows-2019
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
    - uses: actions/checkout@v2
    - name: configure
      shell: cmd
      run: git submodule update --init --recursive
    - name: generate project
      shell: cmd
      run: mkdir build && cd build && cmake .. && dir
    - name: build
      shell: cmd
      run: |
        "%MSBUILD_PATH%\MSBuild.exe" Application.sln
