name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      shell: cmd
      run: git submodule update --init --recursive
    - name: generate project
      shell: cmd
      run: mkdir build && cd build && cmake ..
    - name: build
      shell: cmd
      run: MSBuild Application.sln
